### ISSUE TITLE
CssSyntaxError for `//*`

### ISSUE THREAD

**Issue by jeddy3** [shellscape/postcss-less#135]
* Node Version:  10.15.0
* NPM Version: 6.5.0
* postcss Version: 7.0.14
* postcss-less Version: 3.1.2

### LESS

```less
//*
```

### JavaScript

```js
const { parse } = require("postcss-less");
const less = `//*`;
const result = parse(less);
console.log(result);
```

### Errors 

```
node test.js
/Users/jeddy3/Projects/stylelint/node_modules/postcss-less/node_modules/postcss/lib/tokenize.js:50
    throw input.error('Unclosed ' + what, line, pos - offset);
    ^

CssSyntaxError: <css input>:1:2: Unclosed comment
    at Input.error (/Users/jeddy3/Projects/stylelint/node_modules/postcss-less/node_modules/postcss/lib/input.js:130:16)
    at unclosed (/Users/jeddy3/Projects/stylelint/node_modules/postcss-less/node_modules/postcss/lib/tokenize.js:50:17)
    at Object.nextToken (/Users/jeddy3/Projects/stylelint/node_modules/postcss-less/node_modules/postcss/lib/tokenize.js:240:15)
    at LessParser.other (/Users/jeddy3/Projects/stylelint/node_modules/postcss-less/node_modules/postcss/lib/parser.js:153:30)
    at LessParser.other (/Users/jeddy3/Projects/stylelint/node_modules/postcss-less/lib/LessParser.js:158:13)
    at LessParser.parse (/Users/jeddy3/Projects/stylelint/node_modules/postcss-less/node_modules/postcss/lib/parser.js:77:16)
    at parse (/Users/jeddy3/Projects/stylelint/node_modules/postcss-less/lib/index.js:11:12)
    at Object.<anonymous> (/Users/jeddy3/Projects/stylelint/test.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

### Expected Behavior

For the Less code to be parsed as a `Comment` node, assuming `//*` is valid Less.

### Actual Behavior

Throws `CssSyntaxError` error.

### How can we reproduce the behavior?

```js
const { parse } = require("postcss-less");
const less = `//*`;
const result = parse(less);
console.log(result);
```

Ref: https://github.com/stylelint/stylelint/issues/3955

---

Thanks, as always, for your work on this fantastic parser.

**Comment by XhmikosR** [comment]
@shellscape: friendly ping :)

**Comment by shellscape** [comment]
@XhmikosR friendly ping back to submit a PR to resolve this.

**Comment by XhmikosR** [comment]
Obviously, if I knew were it failed I would have done it already. You are more familiar with the codebase.

Anyway.

**Comment by shellscape** [comment]
I took a look at your Github profile and found that you are a talented, successful, seasoned developer, and a member of many organizations - which all point to your ability to recognize and work with a codebase much less complex than many you work with.

I am a new parent getting two hours of sleep per night while trying to work in time to keep all of my projects, and those I contribute to, up to date, while also having the responsibilities to my regular job and newborn child.

When a maintainer bounces a ping back and adds a _help wanted_ or _PR welcome_ label to the issue, they're not asking for a rebuke of a call for help. They're more likely to be requesting that help in earnest. There are real people on the other end of your comments. Keep that in mind in the future.
