### ISSUE TITLE
missing space after class name parse error

### ISSUE THREAD

**Issue by stuprog** [shellscape/postcss-less#166]
* postcss-less Version:3.1.4 
* postcss-less Version:6.0.0

### LESS

```less
.error{
  @{custom-var}{
    border: red; 
  }
}
```

### JavaScript

```
const lessParser = require("postcss-less");

const result = lessParser.parse(`
.error{
  @{custom-var}{
    border: red; 
  }
}
`);

console.log(result);

```

### Errors 

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'postcss/lib/input'
Require stack:
- C:\Users\PC\OneDrive - South Mediterranean University\Desktop\test\node_modules\postcss-less\lib\index.js
- C:\Users\PC\OneDrive - South Mediterranean University\Desktop\test\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:974:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:92:18)←[39m
    at Object.<anonymous> (C:\Users\PC\OneDrive - South Mediterranean University\Desktop\test\node_modules\←[4mpostcss-less←[24m\lib\index.js:3:15)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:974:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\PC\\OneDrive - South Mediterranean University\\Desktop\\test\\node_modules\\postcss-less\\lib\\index.js'←[39m,
    ←[32m'C:\\Users\\PC\\OneDrive - South Mediterranean University\\Desktop\\test\\index.js'←[39m
  ]
}
```

### Expected Behavior
The Less should parse success

### Actual Behavior
throw error 
### How can we reproduce the behavior?
test the code using Visual Studio Code and yarn

**Comment by iChenLei** [comment]
postcss: `8.4.14`
postcss-less: `6.0.0`

works as expected.
