### ISSUE TITLE
Cannot read property '2' of undefined

### ISSUE THREAD

**Issue by Arcanemagus** [shellscape/postcss-less#64]
While being run through `stylelint` (itself being run in the Atom package `linter-stylelint`) the following stack trace was hit while attempting to parse `.border`:

```
TypeError: Cannot read property '2' of undefined
    at LessParser.rule (C:\Users\Landon Abney\.atom\packages\linter-stylelint\node_modules\postcss-less\dist\less-parser.js:64:38)
    at LessParser.createRule (C:\Users\Landon Abney\.atom\packages\linter-stylelint\node_modules\postcss-less\dist\less-parser.js:110:18)
    at LessParser.ruleWithoutBody (C:\Users\Landon Abney\.atom\packages\linter-stylelint\node_modules\postcss-less\dist\less-parser.js:141:18)
    at LessParser.processEndOfRule (C:\Users\Landon Abney\.atom\packages\linter-stylelint\node_modules\postcss-less\dist\less-parser.js:173:22)
    at LessParser.word (C:\Users\Landon Abney\.atom\packages\linter-stylelint\node_modules\postcss-less\dist\less-parser.js:272:44)
    at LessParser.loop (C:\Users\Landon Abney\.atom\packages\linter-stylelint\node_modules\postcss-less\dist\less-parser.js:300:30)
    at lessParse (C:\Users\Landon Abney\.atom\packages\linter-stylelint\node_modules\postcss-less\dist\less-parse.js:23:12)
    at new LazyResult (C:\Users\Landon Abney\.atom\packages\linter-stylelint\node_modules\postcss\lib\lazy-result.js:70:24)
    at Processor.process (C:\Users\Landon Abney\.atom\packages\linter-stylelint\node_modules\postcss\lib\processor.js:117:12)
    at file:///C:/Users/Landon Abney/Documents/GitHub-release/linter-stylelint/node_modules/stylelint/lib/getPostcssResult.js:81:29
```

You can reproduce this by:

* Install Atom, `linter-stylelint` and open a new `.less` file.
* Start typing out a class name, at some point during typing it you will get a popup of the `Cannot read property '2' of undefined` error
* You can get a stack trace by placing a breakpoint [here](https://github.com/AtomLinter/linter-stylelint/blob/v3.8.1/lib/index.js#L202)

I'm sure there are more direct ways of triggering this 😛.

_Note: Originally filed as https://github.com/AtomLinter/linter-stylelint/issues/181_

**Comment by shellscape** [comment]
I'm gonna close this one as I've started participating in the discussion about this error in the linter-styelint repo. Thanks for reporting it

**Comment by Arcanemagus** [comment]
Keeping the discussion over here, since the bug is within the `less-parser.js` code.

Using `.foo` as the entire contents of the LESS file (note the lack of a newline at the end!).

If you follow the steps above, and additionally place a breakpoint [here](https://github.com/shellscape/postcss-less/blob/v0.16.0/lib/less-parser.js#L20) you can see that `tokens` is an empty array when you attempt to access the property `2` of the first element of it.

As you requested over in https://github.com/AtomLinter/linter-stylelint/issues/181#issuecomment-299353722 I tried to reproduce this using the plain `parse` but I get a different error:

_test.js_
```js
const postCssLess = require('postcss-less');
const less = '.foo';
const root = postCssLess.parse(less);
```

```ShellSession
PS C:\Temp\github\linter-stylelint_GH181> node test.js

C:\Temp\github\linter-stylelint_GH181\node_modules\postcss\lib\parser.js:468
        throw this.input.error('Unknown word', token[2], token[3]);
        ^
CssSyntaxError: <css input>:1:1: Unknown word
    at Input.error (C:\Temp\github\linter-stylelint_GH181\node_modules\postcss\lib\input.js:113:22)
    at LessParser.unknownWord (C:\Temp\github\linter-stylelint_GH181\node_modules\postcss\lib\parser.js:468:26)
    at LessParser.other (C:\Temp\github\linter-stylelint_GH181\node_modules\postcss\lib\parser.js:174:14)
    at LessParser.loop (C:\Temp\github\linter-stylelint_GH181\node_modules\postcss\lib\parser.js:81:26)
    at Object.lessParse [as parse] (C:\Temp\github\linter-stylelint_GH181\node_modules\postcss-less\dist\less-parse.js:23:12)
    at Object.<anonymous> (C:\Temp\github\linter-stylelint_GH181\test.js:3:26)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by shellscape** [comment]
Sounds good to me. We'll keep it over here. I can probably use that to get to the bottom of the error. I'm guessing it's not flexible enough in a few places. I can't promise it in the next few days (I have a queue to bring this module up to date as well) but I will get to it (if no one gets to it before me)

**Comment by Arcanemagus** [comment]
It's waited 3 months, I'm sure another bit isn't going to hurt 😉. Anything I can do to help just let me know!

**Comment by shellscape** [comment]
So! I have some updates:

Given invalid LESS/CSS, the parser should simply throw an error. However, because of how postcss-less is setup, it's not. The `Parser` extended from PostCSS isn't tolerant of invalid CSS. Given this code:

```js
const less = '.foo';
const Parser = require('./node_modules/postcss/lib/parser');
const Input = require('./node_modules/postcss/lib/input');
const input = new Input(less, {});
const parser = new Parser(input);

parser.tokenize();
parser.loop();
```

We're presented with this error:

```
CssSyntaxError: <css input>:1:1: Unknown word

> 1 | .foo
    | ^
```

I'm currently exploring two options:

1. Follow the same path and throw an error. 
2. Allow folks to instruct postcss-less to use [postcss-safe-parser](https://github.com/postcss/postcss-safe-parser) 

Thoughts?

**Comment by Arcanemagus** [comment]
> The Atom plugin author is going to have to trap the CSSSyntaxError that's thrown for invalid LESS/CSS as someone types.

Already handled 😉.
